### ISSUE TITLE
Not working in oreo APP compact issue?

### ISSUE THREAD

**Issue by parmarravi** [kizitonwose/colorpreference#7]
I am having this error every time when i add the colorprefrence in my gradle and then run it in my app.
The Sample app is working but somehow its not working in My app.
This is my style.xml file
```
`    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">#F1433C</item>
        <item name="preferenceTheme">@style/PreferenceThemeOverlay</item>
        <!-- MaterialDrawer specific values -->
        <item name="material_drawer_background">@color/material_drawer_dark_background</item>
        <item name="material_drawer_primary_text">@color/material_drawer_dark_primary_text</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_dark_secondary_text
        </item>
        <item name="material_drawer_hint_text">@color/material_drawer_dark_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_dark_divider</item>
        <item name="material_drawer_selected_text">#F1433C</item>
        <item name="material_drawer_selected">@color/material_drawer_dark_selected</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_dark_primary_text
        </item>
    </style>

    <style name="AppThemeSettings" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">#F1433C</item>
        <item name="preferenceTheme">@style/PreferenceThemeOverlay</item>
    </style>`
```
App crashes as soon as it launches.

`Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity. at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:354) at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323) at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) at com.example.raviprmr21.hub20.MainActivity.onCreate(MainActivity.java:132)`

**Comment by priyankahipoint** [comment]
@parmarravi Have you a got a solution for this?
